# Generated by Django 3.2.5 on 2023-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Apodo', max_length=80, verbose_name='Apodo')),
                ('celular', models.CharField(help_text='Apodo', max_length=80, verbose_name='Número de contacto')),
                ('deuda', models.IntegerField(help_text='Deuda', null=True, verbose_name='Deuda')),
                ('abono', models.IntegerField(help_text='Abono', null=True, verbose_name='Abono')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('estado', models.BooleanField(default=True, help_text='Estado cliente')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
