# Generated by Django 4.2.1 on 2023-06-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_category_name_alter_product_category_and_more'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos', models.ManyToManyField(to='inventory.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='billdetalle',
            name='commonmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='billdetalle',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='billdetalle',
            name='producto',
        ),
        migrations.DeleteModel(
            name='BillBase',
        ),
        migrations.DeleteModel(
            name='BillDetalle',
        ),
    ]
