# Generated by Django 3.2.16 on 2023-02-14 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0002_commonmodel_delete_sharedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmodel',
            name='user_created',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
