# Generated by Django 3.2.5 on 2023-02-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20221125_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción del producto', max_length=200, null=True, verbose_name='Descripcion'),
        ),
    ]
