# Generated by Django 3.2.5 on 2023-02-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_unity', to='inventory.unity', verbose_name='Unidad de medida'),
        ),
    ]
