# Generated by Django 4.1.3 on 2023-03-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_route',
            field=models.ImageField(default='/', upload_to='product_images'),
        ),
    ]
