# Generated by Django 3.2.5 on 2023-03-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_img_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nombre de la Categoria', max_length=80, unique=True, verbose_name='Nombre de la categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_route',
            field=models.ImageField(default='/', upload_to='product_images', verbose_name='Subir imagen'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='Nombre de la Subcategoria', max_length=80, unique=True, verbose_name='Nombre de la categoria'),
        ),
    ]
