# Generated by Django 4.1.7 on 2023-03-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20230324_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='unity',
            name='name',
            field=models.CharField(help_text='Unidad de medida', max_length=80, unique=True, verbose_name='Unidad de medida'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
