# Generated by Django 3.2.5 on 2023-05-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table', '0002_mesa_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ManyToManyField(to='table.Mesa')),
            ],
        ),
    ]
