# Generated by Django 4.1.3 on 2023-03-10 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_mesa', models.IntegerField(help_text='Número de mesa', verbose_name='Número de la mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('estado', models.BooleanField(default=True, help_text='Estado pedido')),
                ('nro_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fkmesa', to='order.mesa')),
            ],
        ),
    ]
