# Generated by Django 3.2.5 on 2023-05-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_mesa_is_active'),
        ('order', '0003_pedido_productos_alter_pedido_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nro_mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fkmesa', to='table.mesa'),
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
