# Generated by Django 4.2.1 on 2023-06-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20230526_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[(1, 'Pendiente'), (2, 'Entregado'), (2, 'Listo')], max_length=20),
        ),
    ]
