# Generated by Django 4.2.1 on 2023-06-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_pedido_autor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_pedido',
            field=models.FloatField(default=0, verbose_name='Total pedido'),
        ),
    ]
