# Generated by Django 4.2.1 on 2023-06-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_pedido_total_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[(1, 'Pendiente'), (2, 'Entregado'), (3, 'Listo')], max_length=20),
        ),
    ]
