# Generated by Django 4.2.1 on 2023-06-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_category_name_alter_product_category_and_more'),
        ('order', '0010_remove_pedido_productos_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='inventory.product'),
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
