# Generated by Django 4.1.7 on 2023-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_mesa', models.IntegerField(help_text='Mesa', verbose_name='Número de la mesa')),
                ('cant_sillas', models.IntegerField(default=0, help_text='Sillas', verbose_name='Cantidad de sillas')),
            ],
        ),
    ]
