# Generated by Django 3.2.5 on 2023-05-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
