# Generated by Django 4.2.1 on 2023-06-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_mesa_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='nro_mesa',
            field=models.IntegerField(help_text='Mesa', unique=True, verbose_name='Número de la mesa'),
        ),
    ]
